logstash:
    image: logstash
    container_name: logstash
    volumes: 
        -  $PWD:/config-dir
    links: 
        - elasticsearch
    command: logstash -f /config-dir/logstash.conf
elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
kibana:
    image: kibana
    container_name: kibana
    ports:
        - "5601:5601"
    links: 
        - elasticsearch
